#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Emzi0767.AndroidBot.Resource", IsApplication=true)]

namespace Emzi0767.AndroidBot
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Iconmini = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int botctl = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int botlog = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int botstatus = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int logitem_text = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int LogItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f04000b
			public const int botctl_off = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int botctl_on = 2130968586;
			
			// aapt resource value: 0x7f04000f
			public const int botrun_running = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public const int botrun_starting = 2130968590;
			
			// aapt resource value: 0x7f040012
			public const int botrun_startup_exception = 2130968594;
			
			// aapt resource value: 0x7f040011
			public const int botrun_stopped = 2130968593;
			
			// aapt resource value: 0x7f040010
			public const int botrun_stopping = 2130968592;
			
			// aapt resource value: 0x7f04000d
			public const int botstatus_off = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int botstatus_on = 2130968588;
			
			// aapt resource value: 0x7f040002
			public const int data_dialog_message = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int data_dialog_no = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int data_dialog_title = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int data_dialog_yes = 2130968579;
			
			// aapt resource value: 0x7f040015
			public const int permission_fail = 2130968597;
			
			// aapt resource value: 0x7f040014
			public const int servicenotif_botopen = 2130968596;
			
			// aapt resource value: 0x7f040013
			public const int servicenotif_botrunning = 2130968595;
			
			// aapt resource value: 0x7f040008
			public const int token_dialog_cancel = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int token_dialog_confirm = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int token_dialog_message = 2130968582;
			
			// aapt resource value: 0x7f040009
			public const int token_dialog_placeholder = 2130968585;
			
			// aapt resource value: 0x7f040005
			public const int token_dialog_title = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
